#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_25 ]; then
	cd $OPENSHIFT_DATA_DIR
	JDK_URL=http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-linux-i586.tar.gz
	wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" ${JDK_URL}
	tar xvf jdk*.tar.gz
	rm -f jdk*.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.2.3 ]; then
	cd $OPENSHIFT_DATA_DIR
	wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.tar.gz
	tar xvf apache-maven*.tar.gz
	rm -f apache-maven*.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]; then
	mkdir $OPENSHIFT_DATA_DIR/m2/repository
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]; then
	mkdir $OPENSHIFT_DATA_DIR/logs
fi

export M2_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.2.3
export MAVEN_OPTS="-Xms128m -Xmx256m"

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_25
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
mvn -s .openshift/settings.xml clean package
