#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]; then
	cd $OPENSHIFT_DATA_DIR
	mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]; then
	cd $OPENSHIFT_DATA_DIR
	mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_20 ]; then
	cd $OPENSHIFT_DATA_DIR
	wget http://www.java.net/download/jdk8u20/archive/b17/binaries/jdk-8u20-ea-bin-b17-linux-x64-04_jun_2014.tar.gz
	tar xvf *.tar.gz
	rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.2.3 ]; then
	cd $OPENSHIFT_DATA_DIR
	wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.tar.gz
	tar xvf *.tar.gz
	rm -f *.tar.gz
fi

export M2_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.2.3
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
mvn -s .openshift/settings.xml clean install

#scp src/main/resources/oauth.properties 544d051be0b8cd509b00001c@vinbudin-compost.rhcloud.com:/var/lib/openshift/544d051be0b8cd509b00001c/app-root/data/oauth.properties