#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

JAVA_SPROPS="-Doauth.properties=${OPENSHIFT_DATA_DIR}/oauth.properties"
BOOT_PARAMS="--server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift"

nohup java -Xms128m -Xmx256m -jar target/*.war ${BOOT_PARAMS} ${JAVA_SPROPS} &