#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

cd $OPENSHIFT_REPO_DIR

export JAVA_HOME=${OPENSHIFT_DATA_DIR}/jdk1.8.0_25

#scp src/main/resources/oauth.properties 544d051be0b8cd509b00001c@vinbudin-compost.rhcloud.com:/var/lib/openshift/544d051be0b8cd509b00001c/app-root/data/oauth.properties

APP_SPROPS="-Doauth.properties=${OPENSHIFT_DATA_DIR}/oauth.properties"
JAVA_OPTS="-Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${OPENSHIFT_DATA_DIR}"
JAVA_OPTS="$JAVA_OPTS -javaagent:${OPENSHIFT_DATA_DIR}/AppDynamicsAgent-3.9.3.0/javaagent.jar"
APP_PARAMS="--server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --logging.config=${OPENSHIFT_DATA_DIR}/logback.xml --spring.profiles.active=openshift"

nohup ${JAVA_HOME}/bin/java -Xms128m -Xmx256m ${JAVA_OPTS} ${APP_SPROPS} -jar target/*.war ${APP_PARAMS} > ${OPENSHIFT_DATA_DIR}/logs/standard.out 2>&1 &